
# 数据源的配置
spring:
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/designrule?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    #最大连接数
    max-active: 30
    min-idle: 5
    max-wait: 10000
    validation-query: SELECT 'x'
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
#先关闭spring对集群session的管理
  session:
    store-type: none
#先关闭security的拦截
#security:
#  basic:
#    enabled: false
#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080

xjy:
  security:
    code:
      image:
        length: 6
        width: 100
        url: /user
#xjy:
#  security:
#    browser:
    #配置这些东西没个/和有/区别很大，没/它会保持原有的部分url，有/它是新的url
#      loginPage: /demo-signin.html
#      loginType: REDIRECT